// 组件库预设色板名称
export const colorPresetNames = [{
    name: '浪漫红',
    enName: 'red',
  }, {
    name: '晚秋红',
    enName: 'orangered',
  }, {
    name: '活力橙',
    enName: 'orange',
  }, {
    name: '黄昏色',
    enName: 'gold',
  }, {
    name: '柠檬黄',
    enName: 'yellow',
  }, {
    name: '新生绿',
    enName: 'lime',
  }, {
    name: '翡翠绿',
    enName: 'green',
  }, {
    name: '碧涛青',
    enName: 'cyan',
  }, {
    name: '海空蓝',
    enName: 'blue',
  }, {
    name: '极致蓝',
    enName: 'deepblue',
  }, {
    name: '暗夜紫',
    enName: 'purple',
  }, {
    name: '青春紫',
    enName: 'pinkpurple',
  }, {
    name: '品红色',
    enName: 'magenta',
  }, {
    name: '中性灰',
    enName: 'grey',
  }]