/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAnchor: typeof import('@arco-design/web-vue')['Anchor']
    AAnchorLink: typeof import('@arco-design/web-vue')['AnchorLink']
    ABadge: typeof import('@arco-design/web-vue')['Badge']
    AButton: typeof import('@arco-design/web-vue')['Button']
    ALink: typeof import('@arco-design/web-vue')['Link']
    AMessage: typeof import('@arco-design/web-vue')['Message']
    ARadio: typeof import('@arco-design/web-vue')['Radio']
    ARadioGroup: typeof import('@arco-design/web-vue')['RadioGroup']
    ATable: typeof import('@arco-design/web-vue')['Table']
    ATag: typeof import('@arco-design/web-vue')['Tag']
    ATypographyText: typeof import('@arco-design/web-vue')['TypographyText']
    ChangeMode: typeof import('./.vitepress/vitepress/components/ChangeMode.vue')['default']
    Colors: typeof import('./.vitepress/vitepress/components/token/Colors.vue')['default']
    CssPrefix: typeof import('./.vitepress/vitepress/components/css/CssPrefix.md')['default']
    Palettes: typeof import('./.vitepress/vitepress/components/Palettes.vue')['default']
    Size: typeof import('./.vitepress/vitepress/components/token/Size.vue')['default']
    Test: typeof import('./.vitepress/vitepress/components/Test.md')['default']
    TipsIntroduce: typeof import('./.vitepress/vitepress/components/docs/tips/TipsIntroduce.md')['default']
    TokenColors: typeof import('./.vitepress/vitepress/components/token/TokenColors.vue')['default']
    TokenLeading: typeof import('./.vitepress/vitepress/components/token/TokenLeading.vue')['default']
    TokenRadius: typeof import('./.vitepress/vitepress/components/token/TokenRadius.vue')['default']
    TokenShade: typeof import('./.vitepress/vitepress/components/token/TokenShade.vue')['default']
    TokenSize: typeof import('./.vitepress/vitepress/components/token/TokenSize.vue')['default']
    TokenWeight: typeof import('./.vitepress/vitepress/components/token/TokenWeight.vue')['default']
  }
}
