/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ATag: typeof import('@arco-design/web-vue')['Tag']
    Palettes: typeof import('./.vitepress/vitepress/components/Palettes.vue')['default']
    Test: typeof import('./.vitepress/vitepress/components/Test.md')['default']
  }
}
